### ISSUE TITLE
با سلام.
من چندین مورد رو با اولویت لوکیشن امتحان کردم اصلا اون لوکیشن نیست مثلا انتخاب آمریکا میشه آلمان.
لوکیشن خیلی مهمتر از نوع کانکشن و نوع پروتکل.
ممنون

### ISSUE THREAD

**Issue by amir385276** [itsyebekhe/HiN-VPN#8]
با سلام.من چندین مورد رو با اولویت لوکیشن امتحان کردم اصلا اون لوکیشن نیست مثلا انتخاب آمریکا میشه آلمان.لوکیشن خیلی مهمتر از نوع کانکشن و نوع پروتکل.ممنون
امروز هم چندين پروتكل و كانفيگ هاي متنوع رو انتخاب كردم ولي جالبه از اين همه كانفيگ يك دونش آمريكا نبود
همش چين و فنلاند و آلمان

لطفا بررسي كنيد

**Comment by amir385276** [comment]
با سلام.من چندین مورد رو با اولویت لوکیشن امتحان کردم اصلا اون لوکیشن نیست مثلا انتخاب آمریکا میشه آلمان.لوکیشن خیلی مهمتر از نوع کانکشن و نوع پروتکل.ممنون
امروز هم چندين پروتكل و كانفيگ هاي متنوع رو انتخاب كردم ولي جالبه از اين همه كانفيگ يك دونش آمريكا نبود
همش چين و فنلاند و آلمان

لطفا بررسي كنيد

**Comment by yebekhe** [comment]
در حال حاضر هیچ راهکار قطعی برای تشخیص لوکیشن وجود نداره چون دیتابیس هایی که برای این مورد وجود داره بسیار اختلاف نظر دارن.
با تشکر
